[general]
db_url = "sqlite:///:memory:" # override path for local db, e.g. "sqlite:///D:\\tradingbot.db"
# strategy_dir = ""  # override path for strategy directory
# log_dir = ""  # override path for log directory
# http_proxy = "http://127.0.0.1:7890"
# https_proxy = "http://127.0.0.1:7890"

# ---------------------------------  Data Fetching API settings ---------------------------------
[source.binance]
api_key = "1234567890abcdef1234567890ABCDEF"
api_secret = "abcdef1234567890ABCDEF1234567890"

# ---------------------------------  Exchange settings ---------------------------------

[exchange.ccxt]
name = "okx"
api_key = "1234567890abcdef1234567890ABCDEF"
secret_key = "abcdef1234567890ABCDEF1234567890"

# ---------------------------------  Logging settings ---------------------------------

[logging]
version = 1
disable_existing_loggers = false

[logging.formatters]
simple = { format = "%(asctime)s [%(levelname)s] %(name)s <%(filename)s:%(lineno)d>: %(message)s", datefmt = "%Y-%m-%d %H:%M:%S" }

[logging.handlers]
console = { class = "logging.StreamHandler", level = "DEBUG", formatter = "simple", stream = "ext://sys.stdout" }
file = { class = "logging.handlers.TimedRotatingFileHandler", level = "INFO", formatter = "simple", filename = "tradingbot.log", when = "midnight", encoding = "utf8" }

[logging.loggers]
tradingbot = { level = "INFO", handlers = [
    "console",
    "file",
], propagate = false }

[logging.root]
level = "INFO"
handlers = ["console"]
